version: '3.6'
services:
  redisdb:
    image: redis
    ports:
      - "6379:6379"
  db:
    image: postgres
    restart: always
    ports:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: anhthong1
      POSTGRES_DB: simplehttp
  api:
    image: service:latest
    ports:
      - 5000:5000
    volumes:
      - ./:/Volumes/HDWEBSOFT/golang/finalProject
    links:
      - db
      - redisdb
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080