version: '3.6'
services:
  redisdb:
    image: redis
    ports:
      - "6379:6379"
  db:
    image: postgres
    restart: always
    ports:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: anhthong1
      POSTGRES_DB: simplehttp
  product-service:
    build:
      dockerfile: ./cmd/service/product/Dockerfile
      context: .
    ports:
      - 5000:5000
    volumes:
      - ./:/Volumes/HDWEBSOFT/golang/finalProject
    depends_on:
      - db
      - redisdb
  user-service:
    build:
      dockerfile: ./cmd/service/user/Dockerfile
      context: .
    ports:
      - 5001:5001
    volumes:
      - ./:/Volumes/HDWEBSOFT/golang/finalProject
    depends_on:
      - db
      - product-service
      - redisdb
  gateway-service:
    build:
      dockerfile: ./cmd/service/gateway/Dockerfile
      context: .
    ports:
      - 8080:8080
    volumes:
      - ./:/Volumes/HDWEBSOFT/golang/finalProject
    depends_on:
      - product-service
      - user-service
  adminer:
    image: adminer
    restart: always
    ports:
      - 3000:8080