// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/v1/model/product/product.proto

/*
Package product is a generated protocol buffer package.

It is generated from these files:
	proto/v1/model/product/product.proto

It has these top-level messages:
	AddReq
	AddRes
	UpdateReq
	UpdateRes
	DeleteReq
	DeleteRes
	GetReq
	GetRes
	Product
*/
package product

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import proto_v1_model_error "grpc-model/error"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddReq struct {
	Sku      string  `protobuf:"bytes,2,opt,name=sku" json:"sku,omitempty"`
	Name     string  `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Price    float32 `protobuf:"fixed32,4,opt,name=price" json:"price,omitempty"`
	Quantity int32   `protobuf:"varint,5,opt,name=quantity" json:"quantity,omitempty"`
}

func (m *AddReq) Reset()                    { *m = AddReq{} }
func (m *AddReq) String() string            { return proto.CompactTextString(m) }
func (*AddReq) ProtoMessage()               {}
func (*AddReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddReq) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *AddReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddReq) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *AddReq) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type AddRes struct {
	Product *Product                      `protobuf:"bytes,1,opt,name=product" json:"product,omitempty"`
	Error   []*proto_v1_model_error.Error `protobuf:"bytes,2,rep,name=error" json:"error,omitempty"`
}

func (m *AddRes) Reset()                    { *m = AddRes{} }
func (m *AddRes) String() string            { return proto.CompactTextString(m) }
func (*AddRes) ProtoMessage()               {}
func (*AddRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AddRes) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *AddRes) GetError() []*proto_v1_model_error.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type UpdateReq struct {
	Product *Product `protobuf:"bytes,1,opt,name=product" json:"product,omitempty"`
}

func (m *UpdateReq) Reset()                    { *m = UpdateReq{} }
func (m *UpdateReq) String() string            { return proto.CompactTextString(m) }
func (*UpdateReq) ProtoMessage()               {}
func (*UpdateReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UpdateReq) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type UpdateRes struct {
	Product *Product                    `protobuf:"bytes,1,opt,name=product" json:"product,omitempty"`
	Error   *proto_v1_model_error.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *UpdateRes) Reset()                    { *m = UpdateRes{} }
func (m *UpdateRes) String() string            { return proto.CompactTextString(m) }
func (*UpdateRes) ProtoMessage()               {}
func (*UpdateRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UpdateRes) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *UpdateRes) GetError() *proto_v1_model_error.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type DeleteReq struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteReq) Reset()                    { *m = DeleteReq{} }
func (m *DeleteReq) String() string            { return proto.CompactTextString(m) }
func (*DeleteReq) ProtoMessage()               {}
func (*DeleteReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DeleteReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteRes struct {
	Error *proto_v1_model_error.Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *DeleteRes) Reset()                    { *m = DeleteRes{} }
func (m *DeleteRes) String() string            { return proto.CompactTextString(m) }
func (*DeleteRes) ProtoMessage()               {}
func (*DeleteRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DeleteRes) GetError() *proto_v1_model_error.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type GetReq struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetReq) Reset()                    { *m = GetReq{} }
func (m *GetReq) String() string            { return proto.CompactTextString(m) }
func (*GetReq) ProtoMessage()               {}
func (*GetReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetRes struct {
	Product *Product                    `protobuf:"bytes,1,opt,name=product" json:"product,omitempty"`
	Error   *proto_v1_model_error.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *GetRes) Reset()                    { *m = GetRes{} }
func (m *GetRes) String() string            { return proto.CompactTextString(m) }
func (*GetRes) ProtoMessage()               {}
func (*GetRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetRes) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *GetRes) GetError() *proto_v1_model_error.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

// define Structure
type Product struct {
	Id       int32   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Sku      string  `protobuf:"bytes,2,opt,name=sku" json:"sku,omitempty"`
	Name     string  `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Price    float32 `protobuf:"fixed32,4,opt,name=price" json:"price,omitempty"`
	Quantity int32   `protobuf:"varint,5,opt,name=quantity" json:"quantity,omitempty"`
}

func (m *Product) Reset()                    { *m = Product{} }
func (m *Product) String() string            { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()               {}
func (*Product) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Product) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Product) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Product) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func init() {
	proto.RegisterType((*AddReq)(nil), "proto.v1.model.product.AddReq")
	proto.RegisterType((*AddRes)(nil), "proto.v1.model.product.AddRes")
	proto.RegisterType((*UpdateReq)(nil), "proto.v1.model.product.UpdateReq")
	proto.RegisterType((*UpdateRes)(nil), "proto.v1.model.product.UpdateRes")
	proto.RegisterType((*DeleteReq)(nil), "proto.v1.model.product.DeleteReq")
	proto.RegisterType((*DeleteRes)(nil), "proto.v1.model.product.DeleteRes")
	proto.RegisterType((*GetReq)(nil), "proto.v1.model.product.GetReq")
	proto.RegisterType((*GetRes)(nil), "proto.v1.model.product.GetRes")
	proto.RegisterType((*Product)(nil), "proto.v1.model.product.Product")
}

func init() { proto.RegisterFile("proto/v1/model/product/product.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x53, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0x26, 0xdd, 0xda, 0xd9, 0x37, 0x10, 0x09, 0x43, 0xc2, 0x76, 0x30, 0x14, 0x0f, 0xbd, 0x98,
	0xd2, 0x79, 0xf2, 0x22, 0x28, 0xfe, 0xb8, 0x4a, 0xc0, 0x8b, 0x27, 0x6b, 0x13, 0xa4, 0xb8, 0xad,
	0x6d, 0x9a, 0x16, 0xf6, 0xdf, 0x4b, 0x93, 0xce, 0x62, 0xd9, 0x61, 0x88, 0x7a, 0x79, 0x3f, 0xfa,
	0xbd, 0xf7, 0xbd, 0xef, 0x83, 0x06, 0xce, 0x0b, 0x95, 0xeb, 0x3c, 0x6a, 0xe2, 0x68, 0x9d, 0x0b,
	0xb9, 0x8a, 0x0a, 0x95, 0x8b, 0x3a, 0xd5, 0xbb, 0xcc, 0x0c, 0x8c, 0x4f, 0x4d, 0x62, 0x4d, 0xcc,
	0xcc, 0x14, 0xeb, 0xd0, 0x39, 0x1d, 0x6c, 0x4b, 0xa5, 0x72, 0x65, 0xa3, 0xdd, 0x0c, 0x5e, 0xc1,
	0xbb, 0x11, 0x82, 0xcb, 0x12, 0x9f, 0xc0, 0xa8, 0xfa, 0xa8, 0x89, 0x43, 0x51, 0xe8, 0xf3, 0xb6,
	0xc4, 0x18, 0xc6, 0x9b, 0x64, 0x2d, 0xc9, 0xc8, 0x7c, 0x32, 0x35, 0x9e, 0x81, 0x5b, 0xa8, 0x2c,
	0x95, 0x64, 0x4c, 0x51, 0xe8, 0x70, 0xdb, 0xe0, 0x39, 0x1c, 0x95, 0x75, 0xb2, 0xd1, 0x99, 0xde,
	0x12, 0x97, 0xa2, 0xd0, 0xe5, 0x5f, 0x7d, 0xd0, 0x74, 0x17, 0x2a, 0x7c, 0x05, 0x93, 0x4e, 0x18,
	0x41, 0x14, 0x85, 0xd3, 0xe5, 0x19, 0xdb, 0xaf, 0x9b, 0x3d, 0xd9, 0xcc, 0x77, 0xf3, 0x38, 0x06,
	0xd7, 0xa8, 0x26, 0x0e, 0x1d, 0x85, 0xd3, 0xe5, 0x62, 0xb8, 0x68, 0x2d, 0xdd, 0xb7, 0x91, 0xdb,
	0xc9, 0xe0, 0x01, 0xfc, 0xe7, 0x42, 0x24, 0x5a, 0xb6, 0xe6, 0x7e, 0x7e, 0x3a, 0xd8, 0xf6, 0x3c,
	0xbf, 0x65, 0x01, 0x1d, 0x68, 0x61, 0x01, 0xfe, 0x9d, 0x5c, 0x49, 0x6b, 0xe1, 0x18, 0x9c, 0x4c,
	0x98, 0xab, 0x2e, 0x77, 0x32, 0x11, 0x5c, 0xf7, 0x60, 0xd5, 0x93, 0xa3, 0x83, 0xc9, 0x09, 0x78,
	0x8f, 0x52, 0xef, 0x63, 0x6e, 0x3a, 0xe4, 0xbf, 0xed, 0x96, 0x30, 0xe9, 0x68, 0x86, 0x92, 0xfe,
	0xea, 0xe7, 0xbc, 0x9d, 0xbd, 0xe0, 0x77, 0x55, 0xa4, 0x17, 0xdf, 0x1e, 0xd7, 0x9b, 0x67, 0xb4,
	0x5e, 0x7e, 0x06, 0x00, 0x00, 0xff, 0xff, 0xbe, 0xc4, 0x28, 0x9d, 0x7d, 0x03, 0x00, 0x00,
}
