// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/v1/model/user/user.proto

/*
Package user is a generated protocol buffer package.

It is generated from these files:
	proto/v1/model/user/user.proto

It has these top-level messages:
	DeleteUserReq
	DeleteUserRes
	CreateUserReq
	CreateUserRes
	GetUserReq
	GetUserRes
	User
*/
package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import proto_v1_model_error "finalProject/cmd/service/grpc-model/error"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DeleteUserReq struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteUserReq) Reset()                    { *m = DeleteUserReq{} }
func (m *DeleteUserReq) String() string            { return proto.CompactTextString(m) }
func (*DeleteUserReq) ProtoMessage()               {}
func (*DeleteUserReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DeleteUserReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteUserRes struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteUserRes) Reset()                    { *m = DeleteUserRes{} }
func (m *DeleteUserRes) String() string            { return proto.CompactTextString(m) }
func (*DeleteUserRes) ProtoMessage()               {}
func (*DeleteUserRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DeleteUserRes) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CreateUserReq struct {
	Email    string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	Name     string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
}

func (m *CreateUserReq) Reset()                    { *m = CreateUserReq{} }
func (m *CreateUserReq) String() string            { return proto.CompactTextString(m) }
func (*CreateUserReq) ProtoMessage()               {}
func (*CreateUserReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateUserReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateUserRes struct {
	User  *User                         `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Error []*proto_v1_model_error.Error `protobuf:"bytes,2,rep,name=error" json:"error,omitempty"`
}

func (m *CreateUserRes) Reset()                    { *m = CreateUserRes{} }
func (m *CreateUserRes) String() string            { return proto.CompactTextString(m) }
func (*CreateUserRes) ProtoMessage()               {}
func (*CreateUserRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateUserRes) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CreateUserRes) GetError() []*proto_v1_model_error.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type GetUserReq struct {
	Id int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetUserReq) Reset()                    { *m = GetUserReq{} }
func (m *GetUserReq) String() string            { return proto.CompactTextString(m) }
func (*GetUserReq) ProtoMessage()               {}
func (*GetUserReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetUserReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetUserRes struct {
	User  *User                       `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Error *proto_v1_model_error.Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *GetUserRes) Reset()                    { *m = GetUserRes{} }
func (m *GetUserRes) String() string            { return proto.CompactTextString(m) }
func (*GetUserRes) ProtoMessage()               {}
func (*GetUserRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetUserRes) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *GetUserRes) GetError() *proto_v1_model_error.Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type User struct {
	Id       int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	Name     string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*DeleteUserReq)(nil), "proto.v1.model.user.DeleteUserReq")
	proto.RegisterType((*DeleteUserRes)(nil), "proto.v1.model.user.DeleteUserRes")
	proto.RegisterType((*CreateUserReq)(nil), "proto.v1.model.user.CreateUserReq")
	proto.RegisterType((*CreateUserRes)(nil), "proto.v1.model.user.CreateUserRes")
	proto.RegisterType((*GetUserReq)(nil), "proto.v1.model.user.GetUserReq")
	proto.RegisterType((*GetUserRes)(nil), "proto.v1.model.user.GetUserRes")
	proto.RegisterType((*User)(nil), "proto.v1.model.user.User")
}

func init() { proto.RegisterFile("proto/v1/model/user/user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xdf, 0x4b, 0x84, 0x40,
	0x10, 0xc7, 0xd1, 0xd3, 0xa8, 0x39, 0xae, 0x87, 0xad, 0x07, 0xbb, 0xa2, 0xc4, 0x27, 0x09, 0x6e,
	0x17, 0xaf, 0xff, 0xa0, 0x1f, 0xf4, 0x1a, 0xc2, 0xbd, 0x44, 0x2f, 0xa6, 0x53, 0x18, 0xea, 0x7a,
	0xb3, 0x66, 0xff, 0x7e, 0x38, 0x0b, 0x5d, 0x59, 0x41, 0xd0, 0xbd, 0x8c, 0xce, 0x7e, 0x3f, 0x33,
	0xfb, 0x9d, 0x61, 0xe1, 0xb4, 0x25, 0xdd, 0x69, 0xd5, 0x27, 0xaa, 0xd6, 0x05, 0x56, 0xea, 0xd5,
	0x20, 0x71, 0x90, 0x2c, 0x88, 0x03, 0xfe, 0xc8, 0x3e, 0x91, 0xac, 0xcb, 0x41, 0x9a, 0x87, 0xa3,
	0x22, 0x24, 0xd2, 0x64, 0xa3, 0x2d, 0x8b, 0xce, 0x60, 0x76, 0x8d, 0x15, 0x76, 0xb8, 0x32, 0x48,
	0x29, 0xae, 0xc5, 0x3e, 0xb8, 0x65, 0x11, 0x38, 0xa1, 0x13, 0xfb, 0xa9, 0x5b, 0x16, 0x63, 0xc0,
	0x7c, 0x03, 0x56, 0x30, 0xbb, 0x22, 0xcc, 0x36, 0x1d, 0x0e, 0xc1, 0xc7, 0x3a, 0x2b, 0xab, 0xc0,
	0x0d, 0x9d, 0x78, 0x2f, 0xb5, 0x89, 0x98, 0xc3, 0x6e, 0x9b, 0x19, 0xf3, 0xa6, 0xa9, 0x08, 0x26,
	0x2c, 0x7c, 0xe4, 0x42, 0x80, 0xd7, 0x64, 0x35, 0x06, 0x1e, 0x9f, 0xf3, 0x7f, 0xb4, 0xfe, 0xda,
	0xd6, 0x88, 0x05, 0x78, 0xc3, 0x4c, 0x7c, 0xf3, 0x74, 0x79, 0x24, 0x7f, 0x98, 0x57, 0x32, 0xcb,
	0x98, 0x48, 0xc0, 0xe7, 0x39, 0x03, 0x37, 0x9c, 0xc4, 0xd3, 0xe5, 0xf1, 0x98, 0xb7, 0x4b, 0xb8,
	0x19, 0x62, 0x6a, 0xc9, 0xe8, 0x04, 0xe0, 0x16, 0xbb, 0xdf, 0x16, 0xd1, 0x7c, 0x52, 0xff, 0xe3,
	0xc6, 0xf9, 0xa3, 0x9b, 0x07, 0xf0, 0x86, 0x06, 0x63, 0x1f, 0xdb, 0x59, 0xef, 0xe5, 0xf9, 0x7d,
	0xfc, 0x54, 0x36, 0x59, 0x75, 0x47, 0xfa, 0x05, 0xf3, 0x4e, 0xe5, 0x75, 0xa1, 0x0c, 0x52, 0x5f,
	0xe6, 0xa8, 0x9e, 0xa9, 0xcd, 0x17, 0x9b, 0x57, 0xf6, 0xb8, 0xc3, 0x66, 0x2f, 0xde, 0x03, 0x00,
	0x00, 0xff, 0xff, 0xf3, 0xed, 0x2b, 0x7e, 0x83, 0x02, 0x00, 0x00,
}
