basePath: /api/v1
host: localhost:8080
info:
  contact:
    email: nguyenanhthong1995@gmail.com
    name: API Support
    url: http://www.swagger.io/support
  description: This is a server build by golang.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Thong API
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
  BasicAuth:
    type: basic
swagger: "2.0"
