// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/v1/user-service.proto

/*
Package service is a generated protocol buffer package.

It is generated from these files:
	proto/v1/user-service.proto

It has these top-level messages:
*/
package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import proto_v1_model_user "grpc-model/user"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UserService service

type UserServiceClient interface {
	RegisterUser(ctx context.Context, in *proto_v1_model_user.CreateUserReq, opts ...grpc.CallOption) (*proto_v1_model_user.CreateUserRes, error)
	DeleteUser(ctx context.Context, in *proto_v1_model_user.DeleteUserReq, opts ...grpc.CallOption) (*proto_v1_model_user.DeleteUserRes, error)
	GetUser(ctx context.Context, in *proto_v1_model_user.GetUserReq, opts ...grpc.CallOption) (*proto_v1_model_user.GetUserRes, error)
	Login(ctx context.Context, in *proto_v1_model_user.LoginReq, opts ...grpc.CallOption) (*proto_v1_model_user.GetUserRes, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) RegisterUser(ctx context.Context, in *proto_v1_model_user.CreateUserReq, opts ...grpc.CallOption) (*proto_v1_model_user.CreateUserRes, error) {
	out := new(proto_v1_model_user.CreateUserRes)
	err := grpc.Invoke(ctx, "/proto.v1.userService.UserService/RegisterUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteUser(ctx context.Context, in *proto_v1_model_user.DeleteUserReq, opts ...grpc.CallOption) (*proto_v1_model_user.DeleteUserRes, error) {
	out := new(proto_v1_model_user.DeleteUserRes)
	err := grpc.Invoke(ctx, "/proto.v1.userService.UserService/DeleteUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUser(ctx context.Context, in *proto_v1_model_user.GetUserReq, opts ...grpc.CallOption) (*proto_v1_model_user.GetUserRes, error) {
	out := new(proto_v1_model_user.GetUserRes)
	err := grpc.Invoke(ctx, "/proto.v1.userService.UserService/GetUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Login(ctx context.Context, in *proto_v1_model_user.LoginReq, opts ...grpc.CallOption) (*proto_v1_model_user.GetUserRes, error) {
	out := new(proto_v1_model_user.GetUserRes)
	err := grpc.Invoke(ctx, "/proto.v1.userService.UserService/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceServer interface {
	RegisterUser(context.Context, *proto_v1_model_user.CreateUserReq) (*proto_v1_model_user.CreateUserRes, error)
	DeleteUser(context.Context, *proto_v1_model_user.DeleteUserReq) (*proto_v1_model_user.DeleteUserRes, error)
	GetUser(context.Context, *proto_v1_model_user.GetUserReq) (*proto_v1_model_user.GetUserRes, error)
	Login(context.Context, *proto_v1_model_user.LoginReq) (*proto_v1_model_user.GetUserRes, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto_v1_model_user.CreateUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.v1.userService.UserService/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RegisterUser(ctx, req.(*proto_v1_model_user.CreateUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto_v1_model_user.DeleteUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.v1.userService.UserService/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteUser(ctx, req.(*proto_v1_model_user.DeleteUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto_v1_model_user.GetUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.v1.userService.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*proto_v1_model_user.GetUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto_v1_model_user.LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.v1.userService.UserService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Login(ctx, req.(*proto_v1_model_user.LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.v1.userService.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUser",
			Handler:    _UserService_RegisterUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UserService_DeleteUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _UserService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/user-service.proto",
}

func init() { proto.RegisterFile("proto/v1/user-service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 193 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x33, 0xd4, 0x2f, 0x2d, 0x4e, 0x2d, 0xd2, 0x2d, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c,
	0x4e, 0xd5, 0x03, 0x8b, 0x0a, 0x89, 0x80, 0x29, 0xbd, 0x32, 0x43, 0x3d, 0x90, 0x64, 0x30, 0x44,
	0x4e, 0x4a, 0x0e, 0xae, 0x25, 0x37, 0x3f, 0x25, 0x35, 0x07, 0xac, 0x11, 0x4c, 0x40, 0x74, 0x19,
	0x5d, 0x64, 0xe2, 0xe2, 0x0e, 0x45, 0xa8, 0x17, 0x0a, 0xe3, 0xe2, 0x09, 0x4a, 0x4d, 0xcf, 0x2c,
	0x2e, 0x49, 0x2d, 0x02, 0x09, 0x0b, 0x29, 0xe9, 0xc1, 0x8d, 0x05, 0x1b, 0x00, 0x36, 0x5c, 0xcf,
	0xb9, 0x28, 0x35, 0xb1, 0x24, 0x15, 0xa4, 0x20, 0x28, 0xb5, 0x50, 0x8a, 0xb0, 0x9a, 0x62, 0xa1,
	0x10, 0x2e, 0x2e, 0x97, 0xd4, 0x9c, 0x54, 0x88, 0x00, 0x0e, 0x53, 0x11, 0x0a, 0x70, 0x9b, 0x8a,
	0xac, 0xa6, 0x58, 0xc8, 0x9b, 0x8b, 0xdd, 0x3d, 0xb5, 0x04, 0x6c, 0xa4, 0x3c, 0x56, 0xe5, 0x50,
	0x59, 0x90, 0x79, 0x04, 0x14, 0x14, 0x0b, 0xb9, 0x73, 0xb1, 0xfa, 0xe4, 0xa7, 0x67, 0xe6, 0x09,
	0xc9, 0x62, 0x55, 0x09, 0x96, 0x23, 0xc6, 0x20, 0x27, 0xce, 0x28, 0x76, 0x68, 0xd4, 0x24, 0xb1,
	0x81, 0x95, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xed, 0xe5, 0x34, 0x45, 0xba, 0x01, 0x00,
	0x00,
}
